### ISSUE TITLE
Handle whitespace in paths for the retire task

### ISSUE THREAD

**Issue by balassy** [urbanjs/tools#2]
When the path of the parent folder contains a whitespace (e.g. the project that uses UrbanJS lives in the "C:\My Projects" folder), the retire task fails with the following error:

```
[05:39:56] 'retire' errored after 95 ms
[05:39:56] Error: Command `C:\My Projects\MyApp\node_modules\urbanjs-tools\node_modules\.bin\retire -n` failed with exit code 1
    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:821:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:469:12)
```

I guess the path must be enclosed with quotes when running the retire process.

Thank you for fixing this.

**Comment by tamasmagedli** [comment]
Thanks, nice catch! Fixed in this commit: https://github.com/urbanjs/tools/commit/be91fb5d95be3e1b541053fcdf66a1a117ce66cd

**Comment by balassy** [comment]
Thank you. Eagerly waiting for the next release :)
